[tools]
go = "1.25.6"
hk = "1.2.0"
pkl = "0.28.2"
shellcheck = "0.10.0"
shfmt = "3.11.0"

[env]
DIST_DIR = "dist"

[tasks.init]
description = "initializes the project"
run = [
    "mise install",
    "hk install --mise",
    "mise run build",
]

[tasks.build]
description = "builds the project"
run = [
    "go mod tidy",
    "go build -o ${DIST_DIR}/prosefmt .",
]

[tasks.check]
description = "checks the project"
run = "hk check"

[tasks.fix]
description = "fixes the project"
run = "hk fix"
